version: "3.9"
services:
    n8n:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                N8N_VERSION: "${N8N_VERSION}"
        ports:
            - "5678:5678"
        restart: "no"
